# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PNJList = QtWidgets.QListWidget(self.frame_3)
        self.PNJList.setObjectName("PNJList")
        self.gridLayout_3.addWidget(self.PNJList, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CreateButton = QtWidgets.QPushButton(self.frame_2)
        self.CreateButton.setObjectName("CreateButton")
        self.verticalLayout_2.addWidget(self.CreateButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PaysanBox = QtWidgets.QCheckBox(self.frame_2)
        self.PaysanBox.setObjectName("PaysanBox")
        self.verticalLayout.addWidget(self.PaysanBox)
        self.GuerrierBox = QtWidgets.QCheckBox(self.frame_2)
        self.GuerrierBox.setObjectName("GuerrierBox")
        self.verticalLayout.addWidget(self.GuerrierBox)
        self.PaladinBox = QtWidgets.QCheckBox(self.frame_2)
        self.PaladinBox.setObjectName("PaladinBox")
        self.verticalLayout.addWidget(self.PaladinBox)
        self.MarchandBox = QtWidgets.QCheckBox(self.frame_2)
        self.MarchandBox.setObjectName("MarchandBox")
        self.verticalLayout.addWidget(self.MarchandBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 21))
        self.menubar.setObjectName("menubar")
        self.menuPNJ = QtWidgets.QMenu(self.menubar)
        self.menuPNJ.setObjectName("menuPNJ")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFermer = QtWidgets.QAction(MainWindow)
        self.actionFermer.setObjectName("actionFermer")
        self.actionFermer.triggered.connect(self.close)
        self.menuPNJ.addAction(self.actionFermer)
        self.menubar.addAction(self.menuPNJ.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CreateButton.setText(_translate("MainWindow", "Create"))
        self.PaysanBox.setText(_translate("MainWindow", "Paysan"))
        self.GuerrierBox.setText(_translate("MainWindow", "Guerrier"))
        self.PaladinBox.setText(_translate("MainWindow", "Paladin"))
        self.MarchandBox.setText(_translate("MainWindow", "Marchand"))
        self.menuPNJ.setTitle(_translate("MainWindow", "PNJ"))
        self.actionFermer.setText(_translate("MainWindow", "Fermer"))
